name: Wake Up & Ping Multiple Hugging Face APIs

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  ping-huggingface-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up & Ping Hugging Face Drive Automation API
        run: |
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" "https://abdelrahman-atm-qissah-drive-automation.hf.space")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Hugging Face Drive Automation API is down! Status: $RESPONSE"
            exit 1
          else
            echo "Hugging Face Drive Automation API is up! Status: $RESPONSE"
          fi

  ping-huggingface-clickup:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up & Ping Hugging Face ClickUp Webhook API
        run: |
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" "https://abdelrahman-atm-tash-clickup-webhook.hf.space")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Hugging Face ClickUp Webhook API is down! Status: $RESPONSE"
            exit 1
          else
            echo "Hugging Face ClickUp Webhook API is up! Status: $RESPONSE"
          fi

  ping-huggingface-words-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up & Ping Hugging Face Words Blocker API
        run: |
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" "https://abdelrahman-atm-tash-words-blocker.hf.space")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Hugging Face Words Blocker API is down! Status: $RESPONSE"
            exit 1
          else
            echo "Hugging Face Words Blocker API is up! Status: $RESPONSE"
          fi
