name: Wake Up & Ping Multiple Hugging Face APIs

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  ping-huggingface-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up & Ping Hugging Face Drive Automation API
        run: |
          for i in {1..3}; do  # Try 3 times
            RESPONSE=$(curl -o response.txt -s -w "%{http_code}" "https://abdelrahman-atm-qissah-drive-automation.hf.space")
            cat response.txt  # Print response for debugging
            if [ "$RESPONSE" -eq 200 ]; then
              echo "Drive Automation API is up! Status: $RESPONSE"
              exit 0
            else
              echo "Attempt $i failed. Retrying..."
              sleep 10  # Wait before retrying
            fi
          done
          echo "Drive Automation API failed to wake up! Status: $RESPONSE"
          exit 1

  ping-huggingface-clickup:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up & Ping Hugging Face ClickUp Webhook API
        run: |
          for i in {1..3}; do
            RESPONSE=$(curl -o response.txt -s -w "%{http_code}" "https://abdelrahman-atm-tash-clickup-webhook.hf.space")
            cat response.txt
            if [ "$RESPONSE" -eq 200 ]; then
              echo "ClickUp Webhook API is up! Status: $RESPONSE"
              exit 0
            else
              echo "Attempt $i failed. Retrying..."
              sleep 10
            fi
          done
          echo "ClickUp Webhook API failed to wake up! Status: $RESPONSE"
          exit 1

  ping-huggingface-words-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up & Ping Hugging Face Words Blocker API
        run: |
          for i in {1..3}; do
            RESPONSE=$(curl -o response.txt -s -w "%{http_code}" "https://abdelrahman-atm-tash-words-blocker.hf.space")
            cat response.txt
            if [ "$RESPONSE" -eq 200 ]; then
              echo "Words Blocker API is up! Status: $RESPONSE"
              exit 0
            else
              echo "Attempt $i failed. Retrying..."
              sleep 10
            fi
          done
          echo "Words Blocker API failed to wake up! Status: $RESPONSE"
          exit 1
